namespace Solar_Power_Lookup_Maui.Model
{
    public class SolarModel
    {
        public string City { get; set; }
        public string State { get; set; }
        public float lat { get; set; }
        public float lon { get; set; }
        public int Jan0600 { get; set; }
        public int Jan0700 { get; set; }
        public int Jan0800 { get; set; }
        public int Jan0900 { get; set; }
        public int Jan1000 { get; set; }
        public int Jan1100 { get; set; }
        public int Jan1200 { get; set; }
        public int Jan1300 { get; set; }
        public int Jan1400 { get; set; }
        public int Jan1500 { get; set; }
        public int Jan1600 { get; set; }
        public int Jan1700 { get; set; }
        public int Jan1800 { get; set; }
        public int Jan1900 { get; set; }
        public int Jan2000 { get; set; }
        public int JanAverage { get; set; }
        public int Feb0600 { get; set; }
        public int Feb0700 { get; set; }
        public int Feb0800 { get; set; }
        public int Feb0900 { get; set; }
        public int Feb1000 { get; set; }
        public int Feb1100 { get; set; }
        public int Feb1200 { get; set; }
        public int Feb1300 { get; set; }
        public int Feb1400 { get; set; }
        public int Feb1500 { get; set; }
        public int Feb1600 { get; set; }
        public int Feb1700 { get; set; }
        public int Feb1800 { get; set; }
        public int Feb1900 { get; set; }
        public int Feb2000 { get; set; }
        public int FebAverage { get; set; }
        public int Mar0600 { get; set; }
        public int Mar0700 { get; set; }
        public int Mar0800 { get; set; }
        public int Mar0900 { get; set; }
        public int Mar1000 { get; set; }
        public int Mar1100 { get; set; }
        public int Mar1200 { get; set; }
        public int Mar1300 { get; set; }
        public int Mar1400 { get; set; }
        public int Mar1500 { get; set; }
        public int Mar1600 { get; set; }
        public int Mar1700 { get; set; }
        public int Mar1800 { get; set; }
        public int Mar1900 { get; set; }
        public int Mar2000 { get; set; }
        public int MarAverage { get; set; }
        public int Apr0600 { get; set; }
        public int Apr0700 { get; set; }
        public int Apr0800 { get; set; }
        public int Apr0900 { get; set; }
        public int Apr1000 { get; set; }
        public int Apr1100 { get; set; }
        public int Apr1200 { get; set; }
        public int Apr1300 { get; set; }
        public int Apr1400 { get; set; }
        public int Apr1500 { get; set; }
        public int Apr1600 { get; set; }
        public int Apr1700 { get; set; }
        public int Apr1800 { get; set; }
        public int Apr1900 { get; set; }
        public int Apr2000 { get; set; }
        public int AprAverage { get; set; }
        public int May0600 { get; set; }
        public int May0700 { get; set; }
        public int May0800 { get; set; }
        public int May0900 { get; set; }
        public int May1000 { get; set; }
        public int May1100 { get; set; }
        public int May1200 { get; set; }
        public int May1300 { get; set; }
        public int May1400 { get; set; }
        public int May1500 { get; set; }
        public int May1600 { get; set; }
        public int May1700 { get; set; }
        public int May1800 { get; set; }
        public int May1900 { get; set; }
        public int May2000 { get; set; }
        public int MayAverage { get; set; }
        public int Jun0600 { get; set; }
        public int Jun0700 { get; set; }
        public int Jun0800 { get; set; }
        public int Jun0900 { get; set; }
        public int Jun1000 { get; set; }
        public int Jun1100 { get; set; }
        public int Jun1200 { get; set; }
        public int Jun1300 { get; set; }
        public int Jun1400 { get; set; }
        public int Jun1500 { get; set; }
        public int Jun1600 { get; set; }
        public int Jun1700 { get; set; }
        public int Jun1800 { get; set; }
        public int Jun1900 { get; set; }
        public int Jun2000 { get; set; }
        public int JunAverage { get; set; }
        public int Jul0600 { get; set; }
        public int Jul0700 { get; set; }
        public int Jul0800 { get; set; }
        public int Jul0900 { get; set; }
        public int Jul1000 { get; set; }
        public int Jul1100 { get; set; }
        public int Jul1200 { get; set; }
        public int Jul1300 { get; set; }
        public int Jul1400 { get; set; }
        public int Jul1500 { get; set; }
        public int Jul1600 { get; set; }
        public int Jul1700 { get; set; }
        public int Jul1800 { get; set; }
        public int Jul1900 { get; set; }
        public int Jul2000 { get; set; }
        public int JulAverage { get; set; }
        public int Aug0600 { get; set; }
        public int Aug0700 { get; set; }
        public int Aug0800 { get; set; }
        public int Aug0900 { get; set; }
        public int Aug1000 { get; set; }
        public int Aug1100 { get; set; }
        public int Aug1200 { get; set; }
        public int Aug1300 { get; set; }
        public int Aug1400 { get; set; }
        public int Aug1500 { get; set; }
        public int Aug1600 { get; set; }
        public int Aug1700 { get; set; }
        public int Aug1800 { get; set; }
        public int Aug1900 { get; set; }
        public int Aug2000 { get; set; }
        public int AugAverage { get; set; }
        public int Sep0600 { get; set; }
        public int Sep0700 { get; set; }
        public int Sep0800 { get; set; }
        public int Sep0900 { get; set; }
        public int Sep1000 { get; set; }
        public int Sep1100 { get; set; }
        public int Sep1200 { get; set; }
        public int Sep1300 { get; set; }
        public int Sep1400 { get; set; }
        public int Sep1500 { get; set; }
        public int Sep1600 { get; set; }
        public int Sep1700 { get; set; }
        public int Sep1800 { get; set; }
        public int Sep1900 { get; set; }
        public int Sep2000 { get; set; }
        public int SepAverage { get; set; }
        public int Oct0600 { get; set; }
        public int Oct0700 { get; set; }
        public int Oct0800 { get; set; }
        public int Oct0900 { get; set; }
        public int Oct1000 { get; set; }
        public int Oct1100 { get; set; }
        public int Oct1200 { get; set; }
        public int Oct1300 { get; set; }
        public int Oct1400 { get; set; }
        public int Oct1500 { get; set; }
        public int Oct1600 { get; set; }
        public int Oct1700 { get; set; }
        public int Oct1800 { get; set; }
        public int Oct1900 { get; set; }
        public int Oct2000 { get; set; }
        public int OctAverage { get; set; }
        public int Nov0600 { get; set; }
        public int Nov0700 { get; set; }
        public int Nov0800 { get; set; }
        public int Nov0900 { get; set; }
        public int Nov1000 { get; set; }
        public int Nov1100 { get; set; }
        public int Nov1200 { get; set; }
        public int Nov1300 { get; set; }
        public int Nov1400 { get; set; }
        public int Nov1500 { get; set; }
        public int Nov1600 { get; set; }
        public int Nov1700 { get; set; }
        public int Nov1800 { get; set; }
        public int Nov1900 { get; set; }
        public int Nov2000 { get; set; }
        public int NovAverage { get; set; }
        public int Dec0600 { get; set; }
        public int Dec0700 { get; set; }
        public int Dec0800 { get; set; }
        public int Dec0900 { get; set; }
        public int Dec1000 { get; set; }
        public int Dec1100 { get; set; }
        public int Dec1200 { get; set; }
        public int Dec1300 { get; set; }
        public int Dec1400 { get; set; }
        public int Dec1500 { get; set; }
        public int Dec1600 { get; set; }
        public int Dec1700 { get; set; }
        public int Dec1800 { get; set; }
        public int Dec1900 { get; set; }
        public int Dec2000 { get; set; }
        public int DecAverage { get; set; }
    }
}


